[default]
src = 'contracts/src'
test = 'contracts/test'
out = 'contracts/out'
cache_path = 'contracts/cache'
libs = ['contracts/lib']
verbosity = 2
bytecode_hash = 'none'
solc_version = '0.8.13'
extra_output_files = ['abi']
script = 'contracts/script'