# This render.yaml deploys a web service for each example in the `examples` directory,
# and a Postgres database that all of those services connect to.

services:
  # - type: web
  #   name: ponder-examples-okpc
  #   env: node
  #   rootDir: examples/okpc
  #   buildCommand: pnpm install --filter "."
  #   startCommand: pnpm run start
  #   envVars:
  #     - key: PONDER_RPC_URL_1
  #       sync: false
  #     - key: START_BLOCK
  #       sync: false
  #     - key: POSTGRES_URL
  #       fromDatabase:
  #         name: ponder-examples-db
  #         property: connectionString
  #     - fromGroup: ponder-examples-env # these env vars are only required within the ponder monorepo
  - type: web
    name: ponder-examples-art-gobblers
    env: node
    rootDir: examples/art-gobblers
    buildCommand: pnpm install --filter "."
    startCommand: pnpm run start
    envVars:
      - key: PONDER_RPC_URL_1
        sync: false
      - key: START_BLOCK
        sync: false
      - key: POSTGRES_URL
        fromDatabase:
          name: ponder-examples-db
          property: connectionString
      - fromGroup: ponder-examples-env # these env vars are only required within the ponder monorepo

databases:
  - name: ponder-examples-db
    postgresMajorVersion: 14

envVarGroups:
  - name: ponder-examples-env
    envVars:
      - key: npm_config_LINK_WORKSPACE_PACKAGES
        value: false
      - key: npm_config_LOCKFILE
        value: false
      - key: PONDER_LOG_LEVEL
        value: 4
